### ISSUE TITLE
Error Trying to pull registry - Requesting bear token: invalid status code from registry 403 (Forbidden)

### ISSUE THREAD

**Issue by patrickfleith** [HPI-Information-Systems/TimeEval#56]
Hi, trying to build my own image I go the following error. I'll investigate, but I wondering it there are permission error that prevent me getting the base image from you registry.
`docker build -t my-lof-image ./lof`

Error:
```Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
STEP 1/6: FROM registry.gitlab.hpi.de/akita/i/pyod:0.2.5
Trying to pull registry.gitlab.hpi.de/akita/i/pyod:0.2.5...
Error: error creating build container: initializing source docker://registry.gitlab.hpi.de/akita/i/pyod:0.2.5: Requesting bear token: invalid status code from registry 403 (Forbidden)```

**Comment by wenig** [comment]
Hi @patrickfleith 
Please have a look at [that](https://github.com/HPI-Information-Systems/TimeEval-algorithms/tree/main/0-base-images). You must build the images yourself, including `pyod:0.2.5`. Our registry is not public to the outside. If you have more questions, feel free to ask.
